Legacy_gbdk: Fix inverted pause behavior, Unmute volume when resuming playback
AntonioND/gbt-player pull request #10
Opened 2020-06-10 19:34 UTC by bbbbbr

Hi Again :)

I might be misunderstanding the use, but seems like gbt_pause() does not work entirely as expected. 

EDIT: I see that I'm calling gbt_pause() with the opposite of the expected value. I think I was doing that because when called with (1) to pause and (0) to un-pause, it never resumes playback. 

So I think there might be two different issues here: 

- The pause behavior is the opposite of expected. gbt_pause(1) sets gbt_playing = 1 instead of = 0.
- The volume never gets un-muted when playback is resumed with gbt_pause(0)

Here's a proposed patch to mute on pause and unmute on unpause. I don't use ASM much so this may not be optimally written  Hopefully no bugs (was not sure if AF needs to be push/popped?).

2020-06-27 11:01 UTC, AntonioND commented
Sorry for the late reply! I totally lost the notification of this PR in a lot of other emails...

This PR changing the logic of the pause function, right? If so, I'd like it to go back to how it was before. It may not make logical sense, but there are games out there that may rely on the current behaviour.

The rest seems to be fine, though.

2020-07-01 00:42 UTC, bbbbbr commented
No worries. :)

Here's an updated PR. 

- Fixes mute/unmute for pause
- Leaves the inverted pause behavior as-is
- Adds a note about which values to use for gbt_pause() in the header file

2020-07-03 16:46 UTC, AntonioND requested changes
I'm happy with the changes. Can you replicate them for the RGBDS version?

2020-07-03 16:46 UTC, AntonioND commented on legacy_gbdk/gbdk_example/gbt_player.s
> +	lda	hl,2(sp) ; (Parameter: 1 = un-pause/resume, 0 = pause)
Remove this comment, the function prototype already explains how it works, it's better to not duplicate comments.

2020-07-03 20:19 UTC, bbbbbr commented
Sure, here are two new commits. I don't have a RGBDS environment set up, so perhaps you can verify syntax & such is ok.

2020-07-06 21:36 UTC, AntonioND approved these changes

2020-07-06 21:37 UTC, merged

2020-07-06 21:38 UTC, AntonioND commented
I've tested it and it works, thanks!