jumps past end of song loop to beginning instead of playing garbage
AntonioND/gbt-player pull request #5
Opened 2020-04-07 00:45 UTC by Q-Bert-Reynolds

If there was a Dnn effect in the last pattern of a song, gbt-player played garbage. This patch causes it to loop around to pattern 0 instead - the behavior in OpenMPT. It has the added effect of allowing you to play looping songs with intros.

2020-04-14 23:39 UTC, AntonioND requested changes
Sorry for not replying earlier. Thanks for the fix.

A couple of comments:
- Use ``hl+`` rather than ``hli``.
- Leave a space between the ``;`` and the rest of the comment.
- Add ``:`` to the local label.

Also, you should fix this in the legacy version.

2020-04-14 23:41 UTC, AntonioND commented
Also, the commit message needs to be descriptive. You should write in the message what you have written in the PR. And maybe change the title of the commit to ``Fix behaviour of Dnn in the last pattern of a song``

2020-04-15 14:50 UTC, Q-Bert-Reynolds commented
Commit message updated, style fixed, and I fixed issue in legacy as well.

2020-04-20 22:54 UTC, merged

2020-04-20 22:54 UTC, AntonioND commented
Sorry, I haven't been in the mood to check GitHub for a few days. Thanks for the changes!

2020-04-20 23:41 UTC, AntonioND commented
This fix was a bit broken, by the way: https://github.com/AntonioND/gbt-player/commit/a27fc0ac019e4b6e33f799aac548a9bff08f204a